### ISSUE TITLE
ilp-plugin-btp/ilp-protocol-stream require window object in MV3

### ISSUE THREAD

**Issue by Danisco212** [interledger/web-monetization-projects#2752]
An object of class IlpPluginBtp from package ilp-plugin-btp cannot be initialized in the service worker of a mv3 chrome extension.

Reason: Uncaught ReferenceError: window is not defined

It requires a window object which is not present in the service worker.

#### Temporary resolutions

unplug these packages ilp-plugin-btp and ilp-protocol-stream with ```yarn unplug <package_name>```

in ilp-plugin-btp: replace ```const {crypto} = window``` with ```const{crypto} = self``` in file crypto.js
in ilp-protocol-stream: replace ```const {crypto} = window``` with ```const{crypto} = self``` in file crypto-browser.js

#### TODO
We will need to patch the ILP libs upstream to officially support Service Workers 

- [ ]  [ilp-plugin-btp "browser" polyfill assumes window environment](https://github.com/interledgerjs/ilp-plugin-btp/issues/70)

Look into `exports` field of package.json and see if it supports a worker "condition" export and see if can make PRs to respective repositories:
- [ ] [ilp-plugin-btp](https://github.com/interledgerjs/ilp-plugin-btp)
- [ ] [ilp-protocol-stream](https://github.com/interledgerjs/interledgerjs/tree/master/packages/ilp-protocol-stream)

**Comment by sublimator** [comment]
Look into `exports` field of package.json and see if it supports a worker "condition" export and see if can make PRs to respective repositories:
- [ ] ilp-plugin-btp (https://github.com/interledgerjs/ilp-plugin-btp)
- [ ] [ilp-protocol-stream](https://github.com/interledgerjs/interledgerjs/tree/master/packages/ilp-protocol-stream)
